"""Add AI analysis fields to tickets

Revision ID: 986f9b34438c
Revises: cfa26d1a99f3
Create Date: 2026-06-17 23:36:55.197950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '986f9b34438c'
down_revision: Union[str, Sequence[str], None] = 'cfa26d1a99f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('ai_category', sa.String(length=50), nullable=True))
    op.add_column('tickets', sa.Column('ai_priority', sa.String(length=20), nullable=True))
    op.add_column('tickets', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'analyzed_at')
    op.drop_column('tickets', 'ai_summary')
    op.drop_column('tickets', 'ai_priority')
    op.drop_column('tickets', 'ai_category')
    # ### end Alembic commands ###
