"""Add AI suggested resolution to tickets

Revision ID: d3db9c5df72a
Revises: 986f9b34438c
Create Date: 2026-06-22 23:51:11.735954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3db9c5df72a'
down_revision: Union[str, Sequence[str], None] = '986f9b34438c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('ai_suggested_resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'ai_suggested_resolution')
    # ### end Alembic commands ###
